"""add doctors table

Revision ID: 5864f5d71894
Revises: 2a85fe3b95af
Create Date: 2026-01-14 19:58:31.916369

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5864f5d71894'
down_revision: Union[str, None] = '2a85fe3b95af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doctors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('donor_id', sa.UUID(), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('gender', sa.Enum('male', 'female', name='gender_type'), nullable=True),
    sa.Column('specialization', sa.String(length=150), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('qualification', sa.Text(), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    
    # Create indexes for better query performance
    op.create_index('idx_doctors_user_id', 'doctors', ['user_id'])
    op.create_index('idx_doctors_donor_id', 'doctors', ['donor_id'])
    op.create_index('idx_doctors_specialization', 'doctors', ['specialization'])
    op.create_index('idx_doctors_name', 'doctors', ['last_name', 'first_name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop indexes first
    op.drop_index('idx_doctors_name', table_name='doctors')
    op.drop_index('idx_doctors_specialization', table_name='doctors')
    op.drop_index('idx_doctors_donor_id', table_name='doctors')
    op.drop_index('idx_doctors_user_id', table_name='doctors')
    
    op.drop_table('doctors')
    
    # Drop enum type
    op.execute("DROP TYPE IF EXISTS gender_type")
    # ### end Alembic commands ###

