"""made name columns unique

Revision ID: c54ef7d8d977
Revises: 99a339d962fb
Create Date: 2026-02-14 20:37:29.027568

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c54ef7d8d977'
down_revision: Union[str, None] = '99a339d962fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'equipment', ['name'])
    op.create_unique_constraint(None, 'equipment_categories', ['name'])
    op.create_unique_constraint(None, 'medical_device_categories', ['name'])
    op.create_unique_constraint(None, 'medical_devices', ['name'])
    op.create_unique_constraint(None, 'medicine_categories', ['name'])
    op.create_unique_constraint(None, 'medicines', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'medicines', type_='unique')
    op.drop_constraint(None, 'medicine_categories', type_='unique')
    op.drop_constraint(None, 'medical_devices', type_='unique')
    op.drop_constraint(None, 'medical_device_categories', type_='unique')
    op.drop_constraint(None, 'equipment_categories', type_='unique')
    op.drop_constraint(None, 'equipment', type_='unique')
    # ### end Alembic commands ###
