"""initial

Revision ID: 2a85fe3b95af
Revises: 
Create Date: 2026-01-13 20:19:52.401280

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '2a85fe3b95af'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Pre-computed bcrypt hash for password "admin"
# Generated with: passlib.hash.bcrypt.hash("admin")
ADMIN_PASSWORD_HASH = "$2b$12$IqtVixn5tmt4YZ7RvIWI/.U9sNOPwcxQDozsW7eEU1N8tdanYji6q"


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###
    
    # Create default admin user
    op.execute(
        f"""
        INSERT INTO users (id, username, email, password_hash, first_name, last_name, is_active, created_at, created_by, updated_at, updated_by)
        VALUES (gen_random_uuid(), 'admin', 'admin@medbase.example', '{ADMIN_PASSWORD_HASH}', 'System', 'Administrator', true, NOW(), 'system', NOW(), 'system')
        """
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###

