"""add soft delete to donation items

Revision ID: 842711dd3a54
Revises: 89a35f2560b9
Create Date: 2026-01-23 20:05:49.624184

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '842711dd3a54'
down_revision: Union[str, None] = '89a35f2560b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('donation_equipment_items', sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('donation_medical_device_items', sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('donation_medicine_items', sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('donation_medicine_items', 'is_deleted')
    op.drop_column('donation_medical_device_items', 'is_deleted')
    op.drop_column('donation_equipment_items', 'is_deleted')
    # ### end Alembic commands ###

