"""remove type from thirdparty

Revision ID: 7146ec59d326
Revises: 9c4ca3ae2e81
Create Date: 2026-03-07 17:54:40.273962

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7146ec59d326'
down_revision: Union[str, None] = '9c4ca3ae2e81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('third_parties', 'type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('third_parties', sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
